### ISSUE TITLE
Full support of Ecma

### ISSUE THREAD

**Issue by AugustinMauroy** [PrismarineJS/prismarine-template#11]
I propose that the template be based on the Ecma-script specification and that all new packages/projects be based on full Ecma

**Comment by extremeheat** [comment]
What exactly are you referring to? Can you be more specific?

**Comment by AugustinMauroy** [comment]
https://github.com/PrismarineJS/prismarine-template/blob/86d7d0156cb8507974c7ad3c1bf2e1c53694bc51/example.js
https://github.com/PrismarineJS/prismarine-template/blob/86d7d0156cb8507974c7ad3c1bf2e1c53694bc51/index.js#L7

**Comment by extremeheat** [comment]
Wrong link?

**Comment by AugustinMauroy** [comment]
> Wrong link?

Nop!
I propose that we use the Ecma specification for the template and future projects.
Do you know difference between CJS and ESM ?

**Comment by extremeheat** [comment]
Ah. I was confused since Ecma is a standard organization and EcmaScript is the same as JavaScript. You mean the ES6 module imports(ESM) over commonjs. This has been discussed several times before on GitHub and the Discord, please read through the old conversations. In short, most things are still CJS and there is no need to introduce a big change to ESM. You can already import CJS into an ESM codebase pretty easily. Same cannot he said the other way around.

**Comment by rom1504** [comment]
Yeah CJS is still the recommended module system at least by nodejs

**Comment by AugustinMauroy** [comment]
> Yeah CJS is still the recommended module system at least by nodejs

Not especially, the next-10 team is looking to implement typescript with mjs. Personally I think that in the future we should maximize the use of mjs
